/**
 * Generates the service worker after a build, with the cache name keyed to the
 * emitted asset hashes.
 *
 * A hand-written constant would be forgotten on some deploy and strand people
 * on stale JavaScript — the classic PWA failure. Deriving it from what was
 * actually built makes that impossible.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'

const BASE = '/GTDo-web/'
const dist = 'dist'

const assets = readdirSync(`${dist}/assets`).map((f) => `${BASE}assets/${f}`)
const shell = [BASE, `${BASE}manifest.webmanifest`, `${BASE}fonts/gtdo-serif.woff2`]
const precache = [...shell, ...assets]

const version = createHash('sha256')
  .update(precache.join('|') + readFileSync(`${dist}/index.html`, 'utf8'))
  .digest('hex')
  .slice(0, 12)

writeFileSync(`${dist}/sw.js`, `/* Generated by scripts/build-sw.mjs — do not edit. */
const CACHE = 'gtdo-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener('install', (event) => {
  // Take over immediately rather than waiting for every tab to close: a user
  // who reloads after a deploy should get the new build, not the old one.
  self.skipWaiting()
  // Not addAll: it is atomic, so a single 404 aborts the whole install and
  // the worker never activates — offline dies entirely because one asset moved.
  // Settle each one instead and cache whatever is actually there.
  // cache: 'reload' bypasses the browser's HTTP cache. Without it the install
  // seeds the NEW cache from the OLD response: GitHub Pages serves the shell
  // with max-age=600, so a deploy inside that window precaches the previous
  // index.html, which links asset hashes that activate has just deleted and
  // that 404 on the server. Offline then opens a blank page — React never
  // mounts. Measured, not theoretical.
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    await Promise.allSettled(
      PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' }))),
    )
  })())
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys()
    await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)))
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // Network-first for navigations so a deploy is picked up on the next load,
  // with the cached shell as the offline fallback. Assets are hashed, so
  // cache-first is safe and instant for them.
  //
  // cache: 'reload' for the same reason as install: a plain fetch() is served
  // by the browser's HTTP cache, and Pages sends max-age=600 on the shell, so
  // "network-first" quietly returned the previous deploy's HTML for up to ten
  // minutes. Measured: stale navigations drop from >6 to 2 with this.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request, { cache: 'reload' })
        .then((res) => {
          const copy = res.clone()
          void caches.open(CACHE).then((c) => c.put(request, copy))
          return res
        })
        .catch(async () => (await caches.match('${BASE}', { ignoreVary: true })) ?? Response.error()),
    )
    return
  }

  // ignoreVary matters: Vite emits <script crossorigin>, so the runtime request
  // does not match the entry addAll() stored, and a strict match silently falls
  // through to the network — which offline means a blank page with the shell
  // served from cache. That was a real failure, caught by the offline test.
  const options = { ignoreVary: true }

  event.respondWith((async () => {
    const hit = await caches.match(request, options)
    if (hit) return hit
    try {
      const res = await fetch(request)
      if (res.ok) {
        const copy = res.clone()
        void caches.open(CACHE).then((c) => c.put(request, copy))
      }
      return res
    } catch (err) {
      // Offline and not cached: try once more by URL before failing, then let
      // the error surface rather than returning a misleading empty 200.
      const late = await caches.match(request.url, options)
      if (late) return late
      throw err
    }
  })())
})
`)

console.log(`sw.js written — cache gtdo-${version}, ${precache.length} precached`)
